services:
  uwgit:
    build: .
    container_name: uwgit
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    command: ["/app/uwgit"]
    ports:
      - "3000:3000"
    volumes:
      - ${REPOS_PATH}:${REPOS_PATH}:ro

networks:
  default:
    driver: bridge
